version: '3.12'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ekartdb
      POSTGRES_USER: mario
      POSTGRES_PASSWORD: Postgre@7!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mario -d ekartdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  web:
    build: .
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=ekartdb
      - DB_USER=mario
      - DB_PASSWORD=Postgre@7!
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build: .
    working_dir: /code
    command: celery -A ekart worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=ekartdb
      - DB_USER=mario
      - DB_PASSWORD=Postgre@7!
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: .
    working_dir: /code
    command: celery -A ekart beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=ekartdb
      - DB_USER=mario
      - DB_PASSWORD=Postgre@7!
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data: