# Generated by Django 5.2.6 on 2025-10-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
